#ifndef _UAPI_LINUX_KERNEL_MCP_SCHEMA_H
#define _UAPI_LINUX_KERNEL_MCP_SCHEMA_H

#define KERNEL_MCP_GENL_FAMILY_NAME "KERNEL_MCP"
#define KERNEL_MCP_GENL_FAMILY_VERSION 1

/* Commands: stable numeric IDs, append-only. */
#define KERNEL_MCP_CMD_UNSPEC 0
#define KERNEL_MCP_CMD_PING 1
#define KERNEL_MCP_CMD_PONG 2
#define KERNEL_MCP_CMD_TOOL_REGISTER 3
#define KERNEL_MCP_CMD_TOOL_UNREGISTER 4
#define KERNEL_MCP_CMD_TOKEN_ACQUIRE 5
#define KERNEL_MCP_CMD_TOKEN_RELEASE 6
#define KERNEL_MCP_CMD_AUDIT_QUERY 7
#define KERNEL_MCP_CMD_LIST_TOOLS 8
#define KERNEL_MCP_CMD_AGENT_REGISTER 9
#define KERNEL_MCP_CMD_TOOL_REQUEST 10
#define KERNEL_MCP_CMD_TOOL_DECISION 11
#define KERNEL_MCP_CMD_TOOL_COMPLETE 12

/* Attributes: stable numeric IDs, append-only. */
#define KERNEL_MCP_ATTR_UNSPEC 0
#define KERNEL_MCP_ATTR_REQ_ID 1
#define KERNEL_MCP_ATTR_TOOL_ID 2
#define KERNEL_MCP_ATTR_TOOL_NAME 3
#define KERNEL_MCP_ATTR_AGENT_ID 4
#define KERNEL_MCP_ATTR_TOKEN_COST 5
#define KERNEL_MCP_ATTR_TOKENS_LEFT 6
#define KERNEL_MCP_ATTR_STATUS 7
#define KERNEL_MCP_ATTR_MESSAGE 8
#define KERNEL_MCP_ATTR_UNIX_SOCK_PATH 9
#define KERNEL_MCP_ATTR_PAYLOAD_LEN 10
#define KERNEL_MCP_ATTR_AUDIT_SEQ 11
#define KERNEL_MCP_ATTR_TS_NS 12
#define KERNEL_MCP_ATTR_TOOL_PERM 13
#define KERNEL_MCP_ATTR_TOOL_COST 14
#define KERNEL_MCP_ATTR_PID 15
#define KERNEL_MCP_ATTR_UID 16
#define KERNEL_MCP_ATTR_DECISION 17
#define KERNEL_MCP_ATTR_WAIT_MS 18
#define KERNEL_MCP_ATTR_TOOL_HASH 19
#define KERNEL_MCP_ATTR_EXEC_MS 20

#endif /* _UAPI_LINUX_KERNEL_MCP_SCHEMA_H */
