#ifndef _UAPI_LINUX_KERNEL_MCP_SCHEMA_H
#define _UAPI_LINUX_KERNEL_MCP_SCHEMA_H

#define KERNEL_MCP_GENL_FAMILY_NAME "KERNEL_MCP"
#define KERNEL_MCP_GENL_FAMILY_VERSION 1

/* Commands: stable numeric IDs, append-only. */
#define KERNEL_MCP_CMD_UNSPEC 0
#define KERNEL_MCP_CMD_TOOL_REGISTER 3
#define KERNEL_MCP_CMD_LIST_TOOLS 8
#define KERNEL_MCP_CMD_AGENT_REGISTER 9
#define KERNEL_MCP_CMD_TOOL_REQUEST 10
#define KERNEL_MCP_CMD_TOOL_DECISION 11
#define KERNEL_MCP_CMD_TOOL_COMPLETE 12
#define KERNEL_MCP_CMD_APPROVAL_DECIDE 13
#define KERNEL_MCP_CMD_RESET_TOOLS 14
#define KERNEL_MCP_CMD_MAX KERNEL_MCP_CMD_RESET_TOOLS

/* Attributes: stable numeric IDs, append-only. */
#define KERNEL_MCP_ATTR_UNSPEC 0
#define KERNEL_MCP_ATTR_REQ_ID 1
#define KERNEL_MCP_ATTR_TOOL_ID 2
#define KERNEL_MCP_ATTR_TOOL_NAME 3
#define KERNEL_MCP_ATTR_AGENT_ID 4
#define KERNEL_MCP_ATTR_STATUS 7
#define KERNEL_MCP_ATTR_MESSAGE 8
#define KERNEL_MCP_ATTR_PID 15
#define KERNEL_MCP_ATTR_UID 16
#define KERNEL_MCP_ATTR_DECISION 17
#define KERNEL_MCP_ATTR_TOOL_HASH 19
#define KERNEL_MCP_ATTR_EXEC_MS 20
#define KERNEL_MCP_ATTR_TOOL_RISK_FLAGS 21
#define KERNEL_MCP_ATTR_TICKET_ID 22
#define KERNEL_MCP_ATTR_APPROVAL_DECISION 23
#define KERNEL_MCP_ATTR_APPROVER 24
#define KERNEL_MCP_ATTR_APPROVAL_REASON 25
#define KERNEL_MCP_ATTR_APPROVAL_TTL_MS 26
#define KERNEL_MCP_ATTR_POLICY_ID 27
#define KERNEL_MCP_ATTR_MAX KERNEL_MCP_ATTR_POLICY_ID

/* Static tool risk flags, set from manifest risk_tags by user-space. */
#define KERNEL_MCP_RISK_FILESYSTEM_WRITE (1U << 0)
#define KERNEL_MCP_RISK_FILESYSTEM_DELETE (1U << 1)
#define KERNEL_MCP_RISK_SYSTEM_MUTATION (1U << 2)
#define KERNEL_MCP_RISK_DEVICE_CONTROL (1U << 3)
#define KERNEL_MCP_RISK_EXTERNAL_NETWORK (1U << 4)
#define KERNEL_MCP_RISK_SENSITIVE_READ (1U << 5)
#define KERNEL_MCP_RISK_RESOURCE_INTENSIVE (1U << 6)
#define KERNEL_MCP_RISK_PRIVILEGED (1U << 7)
#define KERNEL_MCP_RISK_IRREVERSIBLE (1U << 8)

#endif /* _UAPI_LINUX_KERNEL_MCP_SCHEMA_H */
