#ifndef _UAPI_LINUX_KERNEL_MCP_SCHEMA_H
#define _UAPI_LINUX_KERNEL_MCP_SCHEMA_H

#define KERNEL_MCP_GENL_FAMILY_NAME "KERNEL_MCP"
#define KERNEL_MCP_GENL_FAMILY_VERSION 1

/* Commands: canonical capability/participant names with stable numeric IDs. */
#define KERNEL_MCP_CMD_UNSPEC 0
#define KERNEL_MCP_CMD_PING 1
#define KERNEL_MCP_CMD_PONG 2
#define KERNEL_MCP_CMD_CAPABILITY_REGISTER 3
#define KERNEL_MCP_CMD_CAPABILITY_UNREGISTER 4
#define KERNEL_MCP_CMD_TOKEN_ACQUIRE 5
#define KERNEL_MCP_CMD_TOKEN_RELEASE 6
#define KERNEL_MCP_CMD_AUDIT_QUERY 7
#define KERNEL_MCP_CMD_LIST_CAPABILITIES 8
#define KERNEL_MCP_CMD_PARTICIPANT_REGISTER 9
#define KERNEL_MCP_CMD_CAPABILITY_REQUEST 10
#define KERNEL_MCP_CMD_CAPABILITY_DECISION 11
#define KERNEL_MCP_CMD_CAPABILITY_COMPLETE 12

/* Attributes: canonical capability/participant names with stable numeric IDs. */
#define KERNEL_MCP_ATTR_UNSPEC 0
#define KERNEL_MCP_ATTR_REQ_ID 1
#define KERNEL_MCP_ATTR_CAPABILITY_ID 2
#define KERNEL_MCP_ATTR_CAPABILITY_NAME 3
#define KERNEL_MCP_ATTR_PARTICIPANT_ID 4
#define KERNEL_MCP_ATTR_TOKEN_COST 5
#define KERNEL_MCP_ATTR_TOKENS_LEFT 6
#define KERNEL_MCP_ATTR_STATUS 7
#define KERNEL_MCP_ATTR_MESSAGE 8
#define KERNEL_MCP_ATTR_UNIX_SOCK_PATH 9
#define KERNEL_MCP_ATTR_PAYLOAD_LEN 10
#define KERNEL_MCP_ATTR_AUDIT_SEQ 11
#define KERNEL_MCP_ATTR_TS_NS 12
#define KERNEL_MCP_ATTR_CAPABILITY_PERM 13
/* CAPABILITY_PERM is retained as legacy metadata; authorization is based on
 * CAPABILITY_REQUIRED_CAPS plus risk/approval policy.
 */
#define KERNEL_MCP_ATTR_CAPABILITY_COST 14
#define KERNEL_MCP_ATTR_PID 15
#define KERNEL_MCP_ATTR_UID 16
#define KERNEL_MCP_ATTR_DECISION 17
#define KERNEL_MCP_ATTR_WAIT_MS 18
#define KERNEL_MCP_ATTR_CAPABILITY_HASH 19
#define KERNEL_MCP_ATTR_EXEC_MS 20
#define KERNEL_MCP_ATTR_CAPABILITY_REQUIRED_CAPS 21
#define KERNEL_MCP_ATTR_CAPABILITY_RISK_LEVEL 22
#define KERNEL_MCP_ATTR_PARTICIPANT_CAPS 23
#define KERNEL_MCP_ATTR_PARTICIPANT_TRUST_LEVEL 24
#define KERNEL_MCP_ATTR_RL_ENABLED 25
#define KERNEL_MCP_ATTR_RL_BURST 26
#define KERNEL_MCP_ATTR_RL_REFILL_TOKENS 27
#define KERNEL_MCP_ATTR_RL_REFILL_JIFFIES 28
#define KERNEL_MCP_ATTR_RL_DEFAULT_COST 29
#define KERNEL_MCP_ATTR_RL_MAX_INFLIGHT_PER_PARTICIPANT 30
#define KERNEL_MCP_ATTR_RL_DEFER_WAIT_MS 31
#define KERNEL_MCP_ATTR_BROKER_ID 32
#define KERNEL_MCP_ATTR_PROVIDER_ID 33
#define KERNEL_MCP_ATTR_EXECUTOR_ID 34
#define KERNEL_MCP_ATTR_LEASE_ID 35
#define KERNEL_MCP_ATTR_CAPABILITY_APPROVAL_MODE 36
#define KERNEL_MCP_ATTR_CAPABILITY_AUDIT_MODE 37
#define KERNEL_MCP_ATTR_CAPABILITY_MAX_INFLIGHT_PER_PARTICIPANT 38
#define KERNEL_MCP_ATTR_PARTICIPANT_FLAGS 39
#define KERNEL_MCP_ATTR_LEASE_EXPIRES_MS 40
#define KERNEL_MCP_ATTR_BROKER_EPOCH 41
#define KERNEL_MCP_ATTR_PROVIDER_INSTANCE_ID 42
#define KERNEL_MCP_ATTR_EXECUTOR_INSTANCE_ID 43
#define KERNEL_MCP_ATTR_REQUEST_FLAGS 44
#define KERNEL_MCP_ATTR_APPROVAL_TOKEN 45
#define KERNEL_MCP_ATTR_APPROVAL_STATE 46
#define KERNEL_MCP_ATTR_PARTICIPANT_TYPE 47

#define KERNEL_MCP_PARTICIPANT_TYPE_UNSPEC 0
#define KERNEL_MCP_PARTICIPANT_TYPE_PLANNER 1
#define KERNEL_MCP_PARTICIPANT_TYPE_BROKER 2

#endif /* _UAPI_LINUX_KERNEL_MCP_SCHEMA_H */
