"""Shared Generic Netlink schema constants for Kernel MCP."""

from __future__ import annotations

from typing import Final

FAMILY_NAME: Final[str] = "KERNEL_MCP"
FAMILY_VERSION: Final[int] = 1

CMD: Final[dict[str, int]] = {
    "UNSPEC": 0,
    "PING": 1,
    "PONG": 2,
    "CAPABILITY_REGISTER": 3,
    "CAPABILITY_UNREGISTER": 4,
    "TOKEN_ACQUIRE": 5,
    "TOKEN_RELEASE": 6,
    "AUDIT_QUERY": 7,
    "LIST_CAPABILITIES": 8,
    "PARTICIPANT_REGISTER": 9,
    "CAPABILITY_REQUEST": 10,
    "CAPABILITY_DECISION": 11,
    "CAPABILITY_COMPLETE": 12,
}

# Deprecated compatibility aliases. Prefer canonical capability/participant keys.
CMD.update(
    {
        "TOOL_REGISTER": CMD["CAPABILITY_REGISTER"],
        "TOOL_UNREGISTER": CMD["CAPABILITY_UNREGISTER"],
        "LIST_TOOLS": CMD["LIST_CAPABILITIES"],
        "AGENT_REGISTER": CMD["PARTICIPANT_REGISTER"],
        "TOOL_REQUEST": CMD["CAPABILITY_REQUEST"],
        "TOOL_DECISION": CMD["CAPABILITY_DECISION"],
        "TOOL_COMPLETE": CMD["CAPABILITY_COMPLETE"],
    }
)

ATTR: Final[dict[str, int]] = {
    "UNSPEC": 0,
    "REQ_ID": 1,
    "CAPABILITY_ID": 2,
    "CAPABILITY_NAME": 3,
    "PARTICIPANT_ID": 4,
    "TOKEN_COST": 5,
    "TOKENS_LEFT": 6,
    "STATUS": 7,
    "MESSAGE": 8,
    "UNIX_SOCK_PATH": 9,
    "PAYLOAD_LEN": 10,
    "AUDIT_SEQ": 11,
    "TS_NS": 12,
    "CAPABILITY_PERM": 13,
    "CAPABILITY_COST": 14,
    "PID": 15,
    "UID": 16,
    "DECISION": 17,
    "WAIT_MS": 18,
    "CAPABILITY_HASH": 19,
    "EXEC_MS": 20,
    "CAPABILITY_REQUIRED_CAPS": 21,
    "CAPABILITY_RISK_LEVEL": 22,
    "PARTICIPANT_CAPS": 23,
    "PARTICIPANT_TRUST_LEVEL": 24,
    "RL_ENABLED": 25,
    "RL_BURST": 26,
    "RL_REFILL_TOKENS": 27,
    "RL_REFILL_JIFFIES": 28,
    "RL_DEFAULT_COST": 29,
    "RL_MAX_INFLIGHT_PER_AGENT": 30,
    "RL_DEFER_WAIT_MS": 31,
    "BROKER_ID": 32,
    "PROVIDER_ID": 33,
    "EXECUTOR_ID": 34,
    "LEASE_ID": 35,
    "CAPABILITY_APPROVAL_MODE": 36,
    "CAPABILITY_AUDIT_MODE": 37,
    "CAPABILITY_MAX_INFLIGHT_PER_PARTICIPANT": 38,
    "PARTICIPANT_FLAGS": 39,
    "LEASE_EXPIRES_MS": 40,
    "BROKER_EPOCH": 41,
    "PROVIDER_INSTANCE_ID": 42,
    "EXECUTOR_INSTANCE_ID": 43,
    "REQUEST_FLAGS": 44,
    "APPROVAL_TOKEN": 45,
    "APPROVAL_STATE": 46,
    "PARTICIPANT_TYPE": 47,
}

# Deprecated compatibility aliases. Prefer canonical capability/participant keys.
ATTR.update(
    {
        "TOOL_ID": ATTR["CAPABILITY_ID"],
        "TOOL_NAME": ATTR["CAPABILITY_NAME"],
        "AGENT_ID": ATTR["PARTICIPANT_ID"],
        "TOOL_PERM": ATTR["CAPABILITY_PERM"],
        "TOOL_COST": ATTR["CAPABILITY_COST"],
        "TOOL_HASH": ATTR["CAPABILITY_HASH"],
        "TOOL_REQUIRED_CAPS": ATTR["CAPABILITY_REQUIRED_CAPS"],
        "TOOL_RISK_LEVEL": ATTR["CAPABILITY_RISK_LEVEL"],
        "AGENT_CAPS": ATTR["PARTICIPANT_CAPS"],
        "AGENT_TRUST_LEVEL": ATTR["PARTICIPANT_TRUST_LEVEL"],
        "TOOL_APPROVAL_MODE": ATTR["CAPABILITY_APPROVAL_MODE"],
        "TOOL_AUDIT_MODE": ATTR["CAPABILITY_AUDIT_MODE"],
        "TOOL_MAX_INFLIGHT_PER_AGENT": ATTR["CAPABILITY_MAX_INFLIGHT_PER_PARTICIPANT"],
        "AGENT_FLAGS": ATTR["PARTICIPANT_FLAGS"],
    }
)
